Repository Unichamada/UNICHAMADA-FRONT-END, pull requests merged in 2024-09, with the labels that each got.

#27 Feature/junior integracao backend
  package.json
  src/api/api.ts
  src/app/(public)/confirma-matricula/page.tsx
  src/app/(public)/evento/[id]/check-in/page.tsx
  src/app/(public)/evento/[id]/detalhar/page.tsx
  src/app/(public)/evento/[id]/detalhar/turma/[turmaId]/components/table-presenca-component.tsx
  src/app/(public)/evento/[id]/detalhar/turma/[turmaId]/importar-aluno/components/Import-file.tsx
  src/app/(public)/evento/[id]/detalhar/turma/[turmaId]/importar-aluno/page.tsx
  src/app/(public)/evento/[id]/detalhar/turma/[turmaId]/page.tsx
  src/app/(public)/evento/[id]/qr-code/page.tsx
  src/app/(public)/evento/adiciona-evento/components/data-picker.tsx
  src/app/(public)/evento/adiciona-evento/components/form.tsx
  src/app/(public)/evento/adiciona-evento/components/input-form.tsx
  src/app/(public)/evento/adiciona-evento/components/mult-selected-turmas.tsx
  src/app/(public)/evento/adiciona-evento/components/mult-selected.tsx
  src/app/(public)/evento/adiciona-evento/page.tsx
  src/app/(public)/evento/page.tsx
  src/app/(public)/leitor-de-qr-code/page.tsx
  src/app/layout.tsx
  src/components/mult-select.tsx
  src/components/query-provider.tsx
  src/components/ui/command.tsx
  src/components/ui/separator.tsx
  src/hooks/use-param-id.ts
  src/services/Evento/dto/create-evento.dto.ts
  src/services/Evento/dto/get-evento-by-id.dto.ts
  src/services/Evento/dto/get-evento.dto.ts
  src/services/Evento/dto/get-presenca-by-turma.dto.ts
  src/services/Evento/index.ts
  src/services/Presenca/dto/create-presenca.dto.ts
  src/services/Presenca/index.ts
  src/services/Turmas/dto/get-turmas.dto.ts
  src/services/Turmas/index.ts
Labels: feature

#30 Refac/junior ajustes usabilidade
  .gitignore
  src/app/(public)/evento/[id]/detalhar/page.tsx
  src/app/(public)/evento/[id]/detalhar/turma/[turmaId]/components/table-presenca-component.tsx
  src/app/(public)/evento/[id]/detalhar/turma/[turmaId]/page.tsx
  src/app/(public)/evento/adiciona-evento/components/form.tsx
  src/app/(public)/evento/adiciona-evento/page.tsx
  src/app/(public)/evento/page.tsx
  src/app/(public)/presenca/[id]/check-in/page.tsx
  src/app/(public)/presenca/[id]/qr-code/page.tsx
  src/components/ui/button.tsx
  src/services/Evento/dto/create-evento.dto.ts
  src/services/Evento/dto/get-presenca-by-turma.dto.ts
  src/services/Presenca/dto/create-presenca.dto.ts
  src/services/Presenca/index.ts
Labels: feature

#38 fix/ Corrige o campo de data no layout de adicionar evento para 2 díg…
  src/app/(private)/evento/adiciona-evento/components/data-picker.tsx
Labels: hotfix

#39 fix: corrige tentativa de renderizacao da lista mesmo nao encontrando…
  src/app/(private)/evento/page.tsx
Labels: hotfix

#40 release/v.1.2
  src/app/(private)/evento/adiciona-evento/components/data-picker.tsx
  src/app/(private)/evento/page.tsx
  src/app/layout.tsx
Labels: hotfix, feature

#43 Refactor/gabriel refatorando componentes
  package.json
  src/app/(private)/evento/[id]/detalhar/page.tsx
  src/app/(private)/evento/[id]/detalhar/turma/[turmaId]/importar-aluno/page.tsx
  src/app/(private)/evento/[id]/detalhar/turma/[turmaId]/page.tsx
  src/app/(private)/evento/adiciona-evento/components/input-form.tsx
  src/app/(private)/evento/adiciona-evento/page.tsx
  src/app/(private)/evento/page.tsx
  src/app/(private)/layout.tsx
  src/app/favicon.ico
  src/app/globals.css
  src/app/layout.tsx
  src/components/bread-crumb.tsx
  src/components/page.tsx
Labels: refactor
